"""empty message

Revision ID: 78341f114aa1
Revises: 
Create Date: 2023-05-26 14:50:02.455718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78341f114aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('table_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_name',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Primary Key'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='Create Time'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
